/**
 * Language: JavaScript (Node.js)
 * Purpose of this file:
 * This file is a backend controller for managing "proposals" (suggested changes to the portfolio).
 * It handles the logic for receiving new design proposals from visitors, storing them in the
 * database or a local fallback, sending email alerts to the admin, and providing administrative
 * functions to approve or reject these proposals. When approved, it updates the live profile data.
 */

// Import the Proposal model which defines the MongoDB schema for architectural proposals
const Proposal = require('../models/Proposal');
// Import the Profile model which defines the MongoDB schema for the live portfolio data
const Profile = require('../models/Profile');
// Import a middleware wrapper to handle async errors cleanly without try-catch blocks everywhere
const asyncHandler = require('../middleware/asyncHandler');
// Import the sendProposalAlert function from the emailService to send email notifications for new proposals
const { sendProposalAlert } = require('../services/emailService');
// Import the Node.js built-in 'fs' (file system) module to read and write files locally
const fs = require('fs');
// Import the Node.js built-in 'path' module to work with file and directory paths safely
const path = require('path');

/**
 * [submitProposal]
 * Function purpose: Accepts a new architectural proposal from a guest user,
 * saves it, and fires an email alert to the admin.
 */
// Export the submitProposal controller function
exports.submitProposal = asyncHandler(async (req, res) => {
    // Extract the suggestedData object from the incoming request body
    const { suggestedData } = req.body;
    
    // Check if the suggestedData actually exists
    if (!suggestedData) {
        // If missing, return a 400 Bad Request error
        return res.status(400).json({ success: false, message: 'ARCHITECTURAL_DATA_REQUIRED' });
    }

    // Generate a temporary/simulated ID in case the database is offline
    let proposalId = 'SIMULATED_' + Date.now();
    // Require mongoose dynamically here to check the database connection state
    const mongoose = require('mongoose');

    // Check if the MongoDB database is currently connected
    if (mongoose.connection.readyState === 1) {
        // If connected, create a new Proposal document using the provided data and the client's IP address
        const proposal = new Proposal({
            suggestedData,
            clientIp: req.headers['x-forwarded-for'] || req.socket.remoteAddress
        });
        // Save the new proposal to the database
        await proposal.save();
        // Update the proposalId variable to the actual ID generated by MongoDB
        proposalId = proposal._id;
    } else {
        // If not connected, log a message that we are operating in portable mode
        console.log(`📡 [PORTABLE_DISPATCH_PROTOCOL]: System is operating without active database. Dispatching to Telemetry.`);
    }

    // TRIGGER_LIVE_EMAIL_DISPATCH
    // We do not 'await' this email dispatch to keep the API response ultra-fast for the user
    // The service handles its own errors internally
    sendProposalAlert(proposalId).catch(err => console.error('LATENT_EMAIL_ERROR:', err));
    
    // Log the successful dispatch to the server console
    console.log(`[SYSTEM_TELEMETRY] NEW_PROPOSAL_DISPATCHED: ${proposalId}`);

    // Respond to the client with a 201 Created status, indicating success
    res.status(201).json({ 
        success: true, 
        message: 'ARCHITECTURAL_PROPOSAL_DISPATCHED. Awaiting administrative approval.',
        proposalId: proposalId 
    });
});


/**
 * [getProposals]
 * Function purpose: Retrieves a list of all proposals for the admin dashboard.
 */
// Export the getProposals controller function
exports.getProposals = asyncHandler(async (req, res) => {
    // Initialize an empty array to hold the proposals
    let proposals = [];
    // Require mongoose to check the database connection state
    const mongoose = require('mongoose');

    // Check if the MongoDB database is connected
    if (mongoose.connection.readyState === 1) {
        // If connected, find all proposals, sort them by newest first, and convert them to plain objects (.lean())
        proposals = await Proposal.find().sort({ createdAt: -1 }).lean();
    } else {
        // If not connected (portable mode), log that proposals were requested but we can't fetch them from DB
        console.log("📡 [Telemetry] Proposals list requested in portable mode.");
    }

    // Respond with a 200 OK status, the total count, and the array of proposals
    res.json({ success: true, count: proposals.length, data: proposals });
});

/**
 * [getProposal]
 * Function purpose: Retrieves a single proposal by its ID.
 */
// Export the getProposal controller function
exports.getProposal = asyncHandler(async (req, res) => {
    // Search the database for a proposal matching the ID provided in the URL parameters
    const proposal = await Proposal.findById(req.params.id);
    // If no proposal is found, return a 404 Not Found error
    if (!proposal) return res.status(404).json({ success: false, message: 'PROPOSAL_NOT_FOUND' });
    // Respond with a 200 OK status and the specific proposal data
    res.json({ success: true, data: proposal });
});

/**
 * [approveProposal]
 * Function purpose: Approves a proposal and synchronizes its suggested changes
 * to the live profile data in both MongoDB and the local JSON file.
 */
// Export the approveProposal controller function
exports.approveProposal = asyncHandler(async (req, res) => {
    // Search the database for the proposal matching the ID provided in the URL
    const proposal = await Proposal.findById(req.params.id);
    // If the proposal doesn't exist, return a 404 Not Found error
    if (!proposal) return res.status(404).json({ success: false, message: 'PROPOSAL_NOT_FOUND' });

    // Check if the proposal has already been approved to prevent duplicate approvals
    if (proposal.status === 'approved') {
        return res.status(400).json({ success: false, message: 'PROPOSAL_ALREADY_APPROVED' });
    }

    // ATOMIC_PROFILE_SYNCHRONIZATION
    // Step 1. Update the live MongoDB profile data if the database is connected
    let profileData = null;
    const mongoose = require('mongoose');

    // Check if the database is connected
    if (mongoose.connection.readyState === 1) {
        // Find the main profile document
        const profile = await Profile.findOne();
        if (profile) {
            // Merge the suggested changes into the live profile document
            Object.assign(profile, proposal.suggestedData);
            // Save the updated profile to the database
            await profile.save();
            // Convert the updated profile to a plain object
            profileData = profile.toObject();
        }
    }

    // Step 2. Always synchronize with the Local JSON file (Master Failover)
    try {
        // Define the path to the main data.json file
        const dataPath = path.join(__dirname, '../data.json');
        // Read and parse the current contents of the local data.json file
        const currentData = JSON.parse(fs.readFileSync(dataPath, 'utf-8'));
        // Merge the current data with the new suggested data from the proposal
        const updatedData = { ...currentData, ...proposal.suggestedData };
        // Write the newly merged data back to the local JSON file
        fs.writeFileSync(dataPath, JSON.stringify(updatedData, null, 2));
        // Log a success message to the server console
        console.log("💾 [Proposal] Local JSON synchronized with approved blueprint.");
    // Catch any errors during the local file writing process
    } catch (err) {
        // Log the error to the console
        console.error("LOCAL_SYNC_ERROR_DURING_APPROVAL:", err.message);
    }

    // Change the status of the proposal to 'approved'
    proposal.status = 'approved';
    // Save the updated proposal status to the database
    await proposal.save();

    // Respond with a 200 OK success message indicating the blueprint was synchronized
    res.json({ success: true, message: 'ARCHITECTURAL_BLUEPRINT_SYNCHRONIZED_SUCCESSFULLY' });
});

/**
 * [rejectProposal]
 * Function purpose: Rejects a specific proposal without applying its changes.
 */
// Export the rejectProposal controller function
exports.rejectProposal = asyncHandler(async (req, res) => {
    // Search the database for the proposal matching the ID provided in the URL
    const proposal = await Proposal.findById(req.params.id);
    // If the proposal doesn't exist, return a 404 Not Found error
    if (!proposal) return res.status(404).json({ success: false, message: 'PROPOSAL_NOT_FOUND' });

    // Change the status of the proposal to 'rejected'
    proposal.status = 'rejected';
    // Save the updated proposal status to the database
    await proposal.save();

    // Respond with a 200 OK success message indicating the proposal was rejected
    res.json({ success: true, message: 'ARCHITECTURAL_PROPOSAL_REJECTED' });
});

